TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) stm32f10x_gpio.o stm32f10x_rcc.o main.o stupid_delay.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


